In [265]:
import numpy as np
import string
from sklearn.model_selection import train_test_split

In [266]:
input_files = ['C:/Users/juan_/Desktop/programación/NLP_ML_DL_UdemyCourse/documents_for_course/Edgar_allan_poe.txt','C:/Users/juan_/Desktop/programación/NLP_ML_DL_UdemyCourse/documents_for_course/Robert_frost.txt']

In [267]:
input_texts = []
labels = []

for label, document in enumerate(input_files):
    print(f"{document} corresponds to label {label}")
    for line in open(document):
        line = line.rstrip().lower()
        if line:
            line = line.translate(str.maketrans("","",string.punctuation))

            input_texts.append(line)
            labels.append(label)

C:/Users/juan_/Desktop/programación/NLP_ML_DL_UdemyCourse/documents_for_course/Edgar_allan_poe.txt corresponds to label 0
C:/Users/juan_/Desktop/programación/NLP_ML_DL_UdemyCourse/documents_for_course/Robert_frost.txt corresponds to label 1


In [268]:
train_text, test_text, Ytrain, Ytest = train_test_split(input_texts, labels)

In [ ]:
# print(train_text)

In [269]:
len(Ytrain), len(Ytest)

(1618, 540)

In [270]:
idx = 1
word2idx = {'<unk>':0}

In [271]:
for text in train_text:
    tokens=text.split()
    for token in tokens:
        if token not in word2idx:
            word2idx[token] = idx
            idx +=1

In [272]:
word2idx

{'<unk>': 0,
 'from': 1,
 'the': 2,
 'high': 3,
 'west': 4,
 'she': 5,
 'makes': 6,
 'a': 7,
 'gentle': 8,
 'cast': 9,
 'in': 10,
 'slightly': 11,
 'sinking': 12,
 'dull': 13,
 'tide': 14,
 'we': 15,
 'came': 16,
 'here': 17,
 'for': 18,
 'home': 19,
 'me': 20,
 'you': 21,
 'know': 22,
 'out': 23,
 'of': 24,
 'which': 25,
 'miraculous': 26,
 'crescent': 27,
 'farmers': 28,
 'around': 29,
 'twice': 30,
 'as': 31,
 'well': 32,
 'off': 33,
 'was': 34,
 'something': 35,
 'brushed': 36,
 'across': 37,
 'my': 38,
 'mind': 39,
 'two': 40,
 'will': 41,
 'leave': 42,
 'an': 43,
 'empty': 44,
 'house': 45,
 'but': 46,
 'i': 47,
 'dont': 48,
 'see': 49,
 'why': 50,
 'it': 51,
 'should': 52,
 'have': 53,
 'to': 54,
 'bear': 55,
 'and': 56,
 'since': 57,
 'coming': 58,
 'up': 59,
 'had': 60,
 'come': 61,
 'posies': 62,
 'on': 63,
 'her': 64,
 'inner': 65,
 'windowsill': 66,
 'bells': 67,
 'estelles': 68,
 'one': 69,
 'neednt': 70,
 'talk': 71,
 'with': 72,
 'thy': 73,
 'dear': 74,
 'name': 75,
 'te

In [ ]:
len(word2idx)

In [273]:
train_text_int = []
test_text_int = []

for text in train_text:
    tokens = text.split()
    line_as_int = [word2idx[token] for token in tokens]
    train_text_int.append(line_as_int)

for text in test_text:
    tokens = text.split()
    line_as_int = [word2idx.get(token,0) for token in tokens]
    test_text_int.append(line_as_int)

In [274]:
test_text_int[100:105]

[[5, 2473, 64, 950, 577, 2, 0, 461],
 [54, 269, 4, 54, 7, 513, 2291, 72, 2, 0],
 [56, 258, 893, 463, 304, 2270, 0],
 [17, 0, 711, 403, 0, 31, 1011, 865],
 [135, 849, 1519, 18, 656, 24, 368, 21, 633, 20]]

In [275]:
V = len(word2idx)

A0 = np.ones((V,V))
pi0 = np.ones(V)

A1 = np.ones((V,V))
pi1 = np.ones(V)

In [276]:
def compute_counts(text_as_int,A,pi):
    for tokens in text_as_int:
        last_idx = None
        for idx in tokens:
            if last_idx is None:
                pi[idx] += 1
            else:
                A[last_idx,idx] +=1

            last_idx = idx

In [277]:
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

In [280]:
print(pi0)

[ 1. 10. 33. ...  1.  1.  1.]


In [281]:
A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [282]:
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [283]:
print(A0)

[[0.00039604 0.00039604 0.00039604 ... 0.00039604 0.00039604 0.00039604]
 [0.000392   0.000392   0.00274402 ... 0.000392   0.000392   0.000392  ]
 [0.00036088 0.00036088 0.00036088 ... 0.00036088 0.00072176 0.00036088]
 ...
 [0.00039604 0.00039604 0.00039604 ... 0.00039604 0.00039604 0.00039604]
 [0.00039588 0.00039588 0.00039588 ... 0.00039588 0.00039588 0.00039588]
 [0.00039604 0.00039604 0.00039604 ... 0.00039604 0.00039604 0.00039604]]


In [284]:
count0 = sum(y== 0 for y in Ytrain)
count1 = sum(y== 1 for y in Ytrain)
total = len(Ytrain)
p0 = count0 / total
p1 = count1 / total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0,p1

(0.3362175525339926, 0.6637824474660075)

In [ ]:
class Classifier:
    def __init__(self,logAs, logpis,logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.K = len(logpriors)

    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]

        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                logprob += logpi[idx]
            else:
                logprob += logA[last_idx, idx]
            
            last_idx = idx

        return logprob

    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            posteriors = [self._compute_log_likelihood(input_,c) + self.logpriors[c] for c in range(self.K)]
            pred = np.argmax(posteriors)
            predictions[i] = pred
        return predictions



In [ ]:
clf = Classifier([logA0, logA1], [logpi0,logpi1],[logp0,logp1])

In [ ]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

In [ ]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

In [ ]:
from sklearn.metrics import confusion_matrix, f1_score

In [ ]:
cm = confusion_matrix(Ytrain, Ptrain)
cm

In [ ]:
cm_test = confusion_matrix(Ytest, Ptest)
cm_test

In [ ]:
f1_score(Ytrain, Ptrain)

In [ ]:
f1_score(Ytest, Ptest)